ppo:
  n_iterations: 200
  val_period: 10
  n_epochs: 1
  minibatch_size: 256
  horizon: 120
  epsilon: 0.2
  gamma: 0.95
  use_gae: false
  gae_lambda: 0.95
  diff_reward: true

baseline_lr: 0.0005
entropy_weight: 0.0
batch_size: 256
reward_scale: 1.0
# lr: 0.0001
lr: 0.0016134816080499328
decay: 0.0008404361781997002
optimizer: Adam
eval_n_routes: 10

eval:
  min_route_len: 2
  max_route_len: 12

dataset:
  type: pickle
  kwargs:
    path: datasets/20_nodes/mixed
    space_scale: 0.6
    demand_scale: 0.2

defaults:
  - _self_
  - experiment: standard
  - model: bestsofar_feb2023
