ppo:
  n_iterations: 1000
  val_period: 10
  n_epochs: 1
  minibatch_size: 16
  horizon: 400
  epsilon: 0.2
  gamma: 0.99
  use_gae: true
  gae_lambda: 0.95
  diff_reward: true

baseline_lr: 0.001
entropy_weight: 0.0
batch_size: 16
reward_scale: 1.0
# lr: 0.0001
lr: 0.0016134816080499328
decay: 0.0008404361781997002
optimizer: Adam
eval_n_routes: 60

eval:
  min_route_len: 12
  max_route_len: 25

dataset:
  type: mumford
  path: datasets/mumford_dataset/Instances
  city: Mumford3

defaults:
  - experiment: standard
  - model: bestsofar_feb2023
  - _self_

experiment:
  cost_function:
    kwargs:
      constraint_violation_weight: 2.0

